/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jabcode_wrapper_SimpleJABCode */

#ifndef _Included_com_jabcode_wrapper_SimpleJABCode
#define _Included_com_jabcode_wrapper_SimpleJABCode
#ifdef __cplusplus
extern "C" {
#endif
#undef com_jabcode_wrapper_SimpleJABCode_COLOR_MODE_4
#define com_jabcode_wrapper_SimpleJABCode_COLOR_MODE_4 4L
#undef com_jabcode_wrapper_SimpleJABCode_COLOR_MODE_8
#define com_jabcode_wrapper_SimpleJABCode_COLOR_MODE_8 8L
#undef com_jabcode_wrapper_SimpleJABCode_COLOR_MODE_16
#define com_jabcode_wrapper_SimpleJABCode_COLOR_MODE_16 16L
#undef com_jabcode_wrapper_SimpleJABCode_COLOR_MODE_32
#define com_jabcode_wrapper_SimpleJABCode_COLOR_MODE_32 32L
#undef com_jabcode_wrapper_SimpleJABCode_COLOR_MODE_64
#define com_jabcode_wrapper_SimpleJABCode_COLOR_MODE_64 64L
#undef com_jabcode_wrapper_SimpleJABCode_COLOR_MODE_128
#define com_jabcode_wrapper_SimpleJABCode_COLOR_MODE_128 128L
#undef com_jabcode_wrapper_SimpleJABCode_COLOR_MODE_256
#define com_jabcode_wrapper_SimpleJABCode_COLOR_MODE_256 256L
/*
 * Class:     com_jabcode_wrapper_SimpleJABCode
 * Method:    generateJABCode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jabcode_wrapper_SimpleJABCode_generateJABCode
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_jabcode_wrapper_SimpleJABCode
 * Method:    generateJABCodeWithColorMode
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_jabcode_wrapper_SimpleJABCode_generateJABCodeWithColorMode
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     com_jabcode_wrapper_SimpleJABCode
 * Method:    decodeJABCode
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jabcode_wrapper_SimpleJABCode_decodeJABCode
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
