// Targeted by JavaCPP version 1.5.9: DO NOT EDIT THIS FILE

package com.jabcode.internal;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

public class JABCodeNative extends com.jabcode.JABCodePresets {
    static { Loader.load(); }

// Parsed from jabcode.h

/**
 * libjabcode - JABCode Encoding/Decoding Library
 *
 * Copyright 2016 by Fraunhofer SIT. All rights reserved.
 * See LICENSE file for full terms of use and distribution.
 *
 * Contact: Huajian Liu <liu\sit.fraunhofer.de>
 *			Waldemar Berchtold <waldemar.berchtold\sit.fraunhofer.de>
 *
 * \file jabcode.h
 * \brief Main libjabcode header
 */

// #ifndef JABCODE_H
// #define JABCODE_H

// #ifdef __cplusplus
// #endif

// #define VERSION "2.0.0"
// #define BUILD_DATE __DATE__

public static final int MAX_SYMBOL_NUMBER =       61;
public static final int MAX_COLOR_NUMBER =        256;
public static final int MAX_SIZE_ENCODING_MODE =  256;
public static final int JAB_ENCODING_MODES =      6;
public static final int ENC_MAX =                 1000000;
public static final int NUMBER_OF_MASK_PATTERNS =	8;

public static final int DEFAULT_SYMBOL_NUMBER = 			1;
public static final int DEFAULT_MODULE_SIZE =				12;
public static final int DEFAULT_COLOR_NUMBER = 			8;
public static final int DEFAULT_MODULE_COLOR_MODE = 		2;
public static final int DEFAULT_ECC_LEVEL =				3;
public static final int DEFAULT_MASKING_REFERENCE = 		7;


public static final int DISTANCE_TO_BORDER =      4;
public static final int MAX_ALIGNMENT_NUMBER =    9;
public static final int COLOR_PALETTE_NUMBER =	4;

public static final int BITMAP_BITS_PER_PIXEL =	32;
public static final int BITMAP_BITS_PER_CHANNEL =	8;
public static final int BITMAP_CHANNEL_COUNT =	4;

public static final int JAB_SUCCESS =		1;
public static final int JAB_FAILURE =		0;

public static final int NORMAL_DECODE =		0;
public static final int COMPATIBLE_DECODE =	1;

// #define VERSION2SIZE(x)		(x * 4 + 17)
// #define SIZE2VERSION(x)		((x - 17) / 4)
// #define MAX(a,b) 			({__typeof__ (a) _a = (a); __typeof__ (b) _b = (b); _a > _b ? _a : _b;})
// #define MIN(a,b) 			({__typeof__ (a) _a = (a); __typeof__ (b) _b = (b); _a < _b ? _a : _b;})

// #define JAB_REPORT_ERROR(x)	{ printf("JABCode Error: "); printf x; printf("\n"); }
// #define JAB_REPORT_INFO(x)	{ printf("JABCode Info: "); printf x; printf("\n"); }

/**
 * \brief 2-dimensional integer vector
*/
public static class jab_vector2d extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public jab_vector2d() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public jab_vector2d(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public jab_vector2d(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public jab_vector2d position(long position) {
        return (jab_vector2d)super.position(position);
    }
    @Override public jab_vector2d getPointer(long i) {
        return new jab_vector2d((Pointer)this).offsetAddress(i);
    }

	public native @Cast("jab_int32") int x(); public native jab_vector2d x(int setter);
	public native @Cast("jab_int32") int y(); public native jab_vector2d y(int setter);
}

/**
 * \brief 2-dimensional float vector
*/
public static class jab_point extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public jab_point() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public jab_point(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public jab_point(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public jab_point position(long position) {
        return (jab_point)super.position(position);
    }
    @Override public jab_point getPointer(long i) {
        return new jab_point((Pointer)this).offsetAddress(i);
    }

	public native @Cast("jab_float") float x(); public native jab_point x(float setter);
	public native @Cast("jab_float") float y(); public native jab_point y(float setter);
}

/**
 * \brief Data structure
*/
public static class jab_data extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public jab_data() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public jab_data(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public jab_data(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public jab_data position(long position) {
        return (jab_data)super.position(position);
    }
    @Override public jab_data getPointer(long i) {
        return new jab_data((Pointer)this).offsetAddress(i);
    }

	public native @Cast("jab_int32") int length(); public native jab_data length(int setter);
	public native @Cast("jab_char") byte data(int i); public native jab_data data(int i, byte setter);
	@MemberGetter public native @Cast("jab_char*") BytePointer data();
}

/**
 * \brief Code bitmap
*/
public static class jab_bitmap extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public jab_bitmap() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public jab_bitmap(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public jab_bitmap(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public jab_bitmap position(long position) {
        return (jab_bitmap)super.position(position);
    }
    @Override public jab_bitmap getPointer(long i) {
        return new jab_bitmap((Pointer)this).offsetAddress(i);
    }

   public native @Cast("jab_int32") int width(); public native jab_bitmap width(int setter);
   public native @Cast("jab_int32") int height(); public native jab_bitmap height(int setter);
   public native @Cast("jab_int32") int bits_per_pixel(); public native jab_bitmap bits_per_pixel(int setter);
   public native @Cast("jab_int32") int bits_per_channel(); public native jab_bitmap bits_per_channel(int setter);
   public native @Cast("jab_int32") int channel_count(); public native jab_bitmap channel_count(int setter);
   public native @Cast("jab_byte") byte pixel(int i); public native jab_bitmap pixel(int i, byte setter);
   @MemberGetter public native @Cast("jab_byte*") BytePointer pixel();
}

/**
 * \brief Symbol parameters
*/
public static class jab_symbol extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public jab_symbol() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public jab_symbol(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public jab_symbol(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public jab_symbol position(long position) {
        return (jab_symbol)super.position(position);
    }
    @Override public jab_symbol getPointer(long i) {
        return new jab_symbol((Pointer)this).offsetAddress(i);
    }

	public native @Cast("jab_int32") int index(); public native jab_symbol index(int setter);
	public native @ByRef jab_vector2d side_size(); public native jab_symbol side_size(jab_vector2d setter);
	public native @Cast("jab_int32") int host(); public native jab_symbol host(int setter);
	public native @Cast("jab_int32") int slaves(int i); public native jab_symbol slaves(int i, int setter);
	@MemberGetter public native @Cast("jab_int32*") IntPointer slaves();
	public native @Cast("jab_int32") int wcwr(int i); public native jab_symbol wcwr(int i, int setter);
	@MemberGetter public native @Cast("jab_int32*") IntPointer wcwr();
	public native jab_data data(); public native jab_symbol data(jab_data setter);
	public native @Cast("jab_byte*") BytePointer data_map(); public native jab_symbol data_map(BytePointer setter);
	public native jab_data metadata(); public native jab_symbol metadata(jab_data setter);
	public native @Cast("jab_byte*") BytePointer matrix(); public native jab_symbol matrix(BytePointer setter);
}

/**
 * \brief Encode parameters
*/
public static class jab_encode extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public jab_encode() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public jab_encode(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public jab_encode(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public jab_encode position(long position) {
        return (jab_encode)super.position(position);
    }
    @Override public jab_encode getPointer(long i) {
        return new jab_encode((Pointer)this).offsetAddress(i);
    }

	public native @Cast("jab_int32") int color_number(); public native jab_encode color_number(int setter);
	public native @Cast("jab_int32") int symbol_number(); public native jab_encode symbol_number(int setter);
	public native @Cast("jab_int32") int module_size(); public native jab_encode module_size(int setter);
	public native @Cast("jab_int32") int master_symbol_width(); public native jab_encode master_symbol_width(int setter);
	public native @Cast("jab_int32") int master_symbol_height(); public native jab_encode master_symbol_height(int setter);
	/** Palette holding used module colors in format RGB */
	public native @Cast("jab_byte*") BytePointer palette(); public native jab_encode palette(BytePointer setter);
	public native jab_vector2d symbol_versions(); public native jab_encode symbol_versions(jab_vector2d setter);
	public native @Cast("jab_byte*") BytePointer symbol_ecc_levels(); public native jab_encode symbol_ecc_levels(BytePointer setter);
	public native @Cast("jab_int32*") IntPointer symbol_positions(); public native jab_encode symbol_positions(IntPointer setter);
	/** Pointer to internal representation of JAB Code symbols */
	public native jab_symbol symbols(); public native jab_encode symbols(jab_symbol setter);
	public native jab_bitmap bitmap(); public native jab_encode bitmap(jab_bitmap setter);
}

/**
 * \brief Decoded metadata
*/
public static class jab_metadata extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public jab_metadata() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public jab_metadata(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public jab_metadata(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public jab_metadata position(long position) {
        return (jab_metadata)super.position(position);
    }
    @Override public jab_metadata getPointer(long i) {
        return new jab_metadata((Pointer)this).offsetAddress(i);
    }

	public native @Cast("jab_boolean") byte default_mode(); public native jab_metadata default_mode(byte setter);
	public native @Cast("jab_byte") byte Nc(); public native jab_metadata Nc(byte setter);
	public native @Cast("jab_byte") byte mask_type(); public native jab_metadata mask_type(byte setter);
	public native @Cast("jab_byte") byte docked_position(); public native jab_metadata docked_position(byte setter);
	public native @ByRef jab_vector2d side_version(); public native jab_metadata side_version(jab_vector2d setter);
	public native @ByRef jab_vector2d ecl(); public native jab_metadata ecl(jab_vector2d setter);
}

/**
 * \brief Decoded symbol
*/
public static class jab_decoded_symbol extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public jab_decoded_symbol() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public jab_decoded_symbol(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public jab_decoded_symbol(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public jab_decoded_symbol position(long position) {
        return (jab_decoded_symbol)super.position(position);
    }
    @Override public jab_decoded_symbol getPointer(long i) {
        return new jab_decoded_symbol((Pointer)this).offsetAddress(i);
    }

	public native @Cast("jab_int32") int index(); public native jab_decoded_symbol index(int setter);
	public native @Cast("jab_int32") int host_index(); public native jab_decoded_symbol host_index(int setter);
	public native @Cast("jab_int32") int host_position(); public native jab_decoded_symbol host_position(int setter);
	public native @ByRef jab_vector2d side_size(); public native jab_decoded_symbol side_size(jab_vector2d setter);
	public native @Cast("jab_float") float module_size(); public native jab_decoded_symbol module_size(float setter);
	public native @ByRef jab_point pattern_positions(int i); public native jab_decoded_symbol pattern_positions(int i, jab_point setter);
	@MemberGetter public native jab_point pattern_positions();
	public native @ByRef jab_metadata metadata(); public native jab_decoded_symbol metadata(jab_metadata setter);
	public native @ByRef jab_metadata slave_metadata(int i); public native jab_decoded_symbol slave_metadata(int i, jab_metadata setter);
	@MemberGetter public native jab_metadata slave_metadata();
	public native @Cast("jab_byte*") BytePointer palette(); public native jab_decoded_symbol palette(BytePointer setter);
	public native jab_data data(); public native jab_decoded_symbol data(jab_data setter);
}


public static native jab_encode createEncode(@Cast("jab_int32") int color_number, @Cast("jab_int32") int symbol_number);
public static native void destroyEncode(jab_encode enc);
public static native @Cast("jab_int32") int generateJABCode(jab_encode enc, jab_data data);
public static native jab_data decodeJABCode(jab_bitmap bitmap, @Cast("jab_int32") int mode, @Cast("jab_int32*") IntPointer status);
public static native jab_data decodeJABCode(jab_bitmap bitmap, @Cast("jab_int32") int mode, @Cast("jab_int32*") IntBuffer status);
public static native jab_data decodeJABCode(jab_bitmap bitmap, @Cast("jab_int32") int mode, @Cast("jab_int32*") int[] status);
public static native jab_data decodeJABCodeEx(jab_bitmap bitmap, @Cast("jab_int32") int mode, @Cast("jab_int32*") IntPointer status, jab_decoded_symbol symbols, @Cast("jab_int32") int max_symbol_number);
public static native jab_data decodeJABCodeEx(jab_bitmap bitmap, @Cast("jab_int32") int mode, @Cast("jab_int32*") IntBuffer status, jab_decoded_symbol symbols, @Cast("jab_int32") int max_symbol_number);
public static native jab_data decodeJABCodeEx(jab_bitmap bitmap, @Cast("jab_int32") int mode, @Cast("jab_int32*") int[] status, jab_decoded_symbol symbols, @Cast("jab_int32") int max_symbol_number);
public static native @Cast("jab_boolean") byte saveImage(jab_bitmap bitmap, @Cast("jab_char*") BytePointer filename);
public static native @Cast("jab_boolean") byte saveImage(jab_bitmap bitmap, @Cast("jab_char*") ByteBuffer filename);
public static native @Cast("jab_boolean") byte saveImage(jab_bitmap bitmap, @Cast("jab_char*") byte[] filename);
public static native @Cast("jab_boolean") byte saveImageCMYK(jab_bitmap bitmap, @Cast("jab_boolean") byte isCMYK, @Cast("jab_char*") BytePointer filename);
public static native @Cast("jab_boolean") byte saveImageCMYK(jab_bitmap bitmap, @Cast("jab_boolean") byte isCMYK, @Cast("jab_char*") ByteBuffer filename);
public static native @Cast("jab_boolean") byte saveImageCMYK(jab_bitmap bitmap, @Cast("jab_boolean") byte isCMYK, @Cast("jab_char*") byte[] filename);
public static native jab_bitmap readImage(@Cast("jab_char*") BytePointer filename);
public static native jab_bitmap readImage(@Cast("jab_char*") ByteBuffer filename);
public static native jab_bitmap readImage(@Cast("jab_char*") byte[] filename);
public static native void reportError(@Cast("jab_char*") BytePointer message);
public static native void reportError(@Cast("jab_char*") ByteBuffer message);
public static native void reportError(@Cast("jab_char*") byte[] message);

// #ifdef __cplusplus
// #endif

// #endif


// Parsed from jabcode_c_wrapper.h

/**
 * JABCode C Wrapper Header
 * This file provides C wrapper functions for the JABCode C++ library
 */

// #ifndef JABCODE_C_WRAPPER_H
// #define JABCODE_C_WRAPPER_H

// #ifdef __cplusplus
// #endif

// Ensure jabcode.h also has C linkage when included in C++ compilation units
// #include "jabcode.h"

// C wrapper functions for JABCode library
public static native @Cast("jab_boolean") byte saveImageCMYK_c(jab_bitmap bitmap, @Cast("jab_boolean") byte isCMYK, @Cast("jab_char*") BytePointer filename);
public static native @Cast("jab_boolean") byte saveImageCMYK_c(jab_bitmap bitmap, @Cast("jab_boolean") byte isCMYK, @Cast("jab_char*") ByteBuffer filename);
public static native @Cast("jab_boolean") byte saveImageCMYK_c(jab_bitmap bitmap, @Cast("jab_boolean") byte isCMYK, @Cast("jab_char*") byte[] filename);
public static native void reportError_c(@Cast("jab_char*") BytePointer message);
public static native void reportError_c(@Cast("jab_char*") ByteBuffer message);
public static native void reportError_c(@Cast("jab_char*") byte[] message);
// Experimental: adjust Nc detection thresholds (for tests)
public static native void setNcThresholds_c(@Cast("jab_int32") int ths_black, @Cast("jab_double") double ths_std);
// Experimental: force Nc value in decoder (for tests)
public static native void setForceNc_c(@Cast("jab_int32") int nc);
// Experimental: fetch last Nc RGB samples (4x RGB), 4 module values, and final Nc
public static native void getLastNcDebug_c(@Cast("jab_int32*") IntPointer out, @Cast("jab_int32") int len);
public static native void getLastNcDebug_c(@Cast("jab_int32*") IntBuffer out, @Cast("jab_int32") int len);
public static native void getLastNcDebug_c(@Cast("jab_int32*") int[] out, @Cast("jab_int32") int len);
// Experimental: use default palette grid for >=16 colors during decode (for tests)
public static native void setUseDefaultPaletteHighColor_c(@Cast("jab_int32") int flag);
// Experimental: force ECL (wc, wr) during decode (for tests)
public static native void setForceEcl_c(@Cast("jab_int32") int wc, @Cast("jab_int32") int wr);
// Experimental: classifier debug controls and stats (for tests)
    public static native void setClassifierDebug_c(@Cast("jab_int32") int enable);
    public static native void setClassifierMode_c(@Cast("jab_int32") int mode);
    public static native void getClassifierStats_c(@Cast("jab_int32*") IntPointer out, @Cast("jab_int32") int len);
    public static native void getClassifierStats_c(@Cast("jab_int32*") IntBuffer out, @Cast("jab_int32") int len);
    public static native void getClassifierStats_c(@Cast("jab_int32*") int[] out, @Cast("jab_int32") int len);

    // Experimental: pipeline debug (for tests)
    public static native void getDecodePipelineDebug_c(@Cast("jab_int32*") IntPointer out, @Cast("jab_int32") int len);
    public static native void getDecodePipelineDebug_c(@Cast("jab_int32*") IntBuffer out, @Cast("jab_int32") int len);
    public static native void getDecodePipelineDebug_c(@Cast("jab_int32*") int[] out, @Cast("jab_int32") int len);
    public static native void getRawModuleSample_c(@Cast("jab_int32*") IntPointer out, @Cast("jab_int32") int len);
    public static native void getRawModuleSample_c(@Cast("jab_int32*") IntBuffer out, @Cast("jab_int32") int len);
    public static native void getRawModuleSample_c(@Cast("jab_int32*") int[] out, @Cast("jab_int32") int len);
    // Experimental: Part II debug (for tests)
    public static native void getPart2Debug_c(@Cast("jab_int32*") IntPointer out, @Cast("jab_int32") int len);
    public static native void getPart2Debug_c(@Cast("jab_int32*") IntBuffer out, @Cast("jab_int32") int len);
    public static native void getPart2Debug_c(@Cast("jab_int32*") int[] out, @Cast("jab_int32") int len);
    // Experimental: force mask type during demask (for tests). Use -1 to disable.
    public static native void setForceMask_c(@Cast("jab_int32") int mask);
    // Experimental: decoder palette dump (first palette block, bytes as ints)
    public static native void getDecoderPaletteDebug_c(@Cast("jab_int32*") IntPointer out, @Cast("jab_int32") int len);
    public static native void getDecoderPaletteDebug_c(@Cast("jab_int32*") IntBuffer out, @Cast("jab_int32") int len);
    public static native void getDecoderPaletteDebug_c(@Cast("jab_int32*") int[] out, @Cast("jab_int32") int len);
    // Experimental: encoder default palette dump for given color_number (bytes as ints)
    public static native void getEncoderDefaultPalette_c(@Cast("jab_int32") int color_number, @Cast("jab_int32*") IntPointer out, @Cast("jab_int32") int len);
    public static native void getEncoderDefaultPalette_c(@Cast("jab_int32") int color_number, @Cast("jab_int32*") IntBuffer out, @Cast("jab_int32") int len);
    public static native void getEncoderDefaultPalette_c(@Cast("jab_int32") int color_number, @Cast("jab_int32*") int[] out, @Cast("jab_int32") int len);

    // Experimental: LDPC input bits before(0)/after(1) deinterleave (bits as ints)
    public static native void getLdpcInputDebug_c(@Cast("jab_int32*") IntPointer out, @Cast("jab_int32") int len, @Cast("jab_int32") int which);
    public static native void getLdpcInputDebug_c(@Cast("jab_int32*") IntBuffer out, @Cast("jab_int32") int len, @Cast("jab_int32") int which);
    public static native void getLdpcInputDebug_c(@Cast("jab_int32*") int[] out, @Cast("jab_int32") int len, @Cast("jab_int32") int which);

// #ifdef __cplusplus
// #endif

// #endif // JABCODE_C_WRAPPER_H


}
