// Targeted by JavaCPP version 1.5.9: DO NOT EDIT THIS FILE

package com.jabcode.wrapper;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

public class JABCodeNative extends com.jabcode.wrapper.JABCodePresets {
    static { Loader.load(); }

// Parsed from jabcode.h

/**
 * libjabcode - JABCode Encoding/Decoding Library
 *
 * Copyright 2016 by Fraunhofer SIT. All rights reserved.
 * See LICENSE file for full terms of use and distribution.
 *
 * Contact: Huajian Liu <liu\sit.fraunhofer.de>
 *			Waldemar Berchtold <waldemar.berchtold\sit.fraunhofer.de>
 *
 * \file jabcode.h
 * \brief Main libjabcode header
 */

// #ifndef JABCODE_H
// #define JABCODE_H

public static native @MemberGetter String VERSION();
public static final String VERSION = VERSION();
public static native @MemberGetter String BUILD_DATE();
public static final String BUILD_DATE = BUILD_DATE();

public static native @MemberGetter int MAX_SYMBOL_NUMBER();
public static final int MAX_SYMBOL_NUMBER = MAX_SYMBOL_NUMBER();
public static native @MemberGetter int MAX_COLOR_NUMBER();
public static final int MAX_COLOR_NUMBER = MAX_COLOR_NUMBER();
public static native @MemberGetter int MAX_SIZE_ENCODING_MODE();
public static final int MAX_SIZE_ENCODING_MODE = MAX_SIZE_ENCODING_MODE();
public static native @MemberGetter int JAB_ENCODING_MODES();
public static final int JAB_ENCODING_MODES = JAB_ENCODING_MODES();
public static native @MemberGetter int ENC_MAX();
public static final int ENC_MAX = ENC_MAX();
public static native @MemberGetter int NUMBER_OF_MASK_PATTERNS();
public static final int NUMBER_OF_MASK_PATTERNS = NUMBER_OF_MASK_PATTERNS();

public static native @MemberGetter int DEFAULT_SYMBOL_NUMBER();
public static final int DEFAULT_SYMBOL_NUMBER = DEFAULT_SYMBOL_NUMBER();
public static native @MemberGetter int DEFAULT_MODULE_SIZE();
public static final int DEFAULT_MODULE_SIZE = DEFAULT_MODULE_SIZE();
public static native @MemberGetter int DEFAULT_COLOR_NUMBER();
public static final int DEFAULT_COLOR_NUMBER = DEFAULT_COLOR_NUMBER();
public static native @MemberGetter int DEFAULT_MODULE_COLOR_MODE();
public static final int DEFAULT_MODULE_COLOR_MODE = DEFAULT_MODULE_COLOR_MODE();
public static native @MemberGetter int DEFAULT_ECC_LEVEL();
public static final int DEFAULT_ECC_LEVEL = DEFAULT_ECC_LEVEL();
public static native @MemberGetter int DEFAULT_MASKING_REFERENCE();
public static final int DEFAULT_MASKING_REFERENCE = DEFAULT_MASKING_REFERENCE();


public static native @MemberGetter int DISTANCE_TO_BORDER();
public static final int DISTANCE_TO_BORDER = DISTANCE_TO_BORDER();
public static native @MemberGetter int MAX_ALIGNMENT_NUMBER();
public static final int MAX_ALIGNMENT_NUMBER = MAX_ALIGNMENT_NUMBER();
public static native @MemberGetter int COLOR_PALETTE_NUMBER();
public static final int COLOR_PALETTE_NUMBER = COLOR_PALETTE_NUMBER();

public static native @MemberGetter int BITMAP_BITS_PER_PIXEL();
public static final int BITMAP_BITS_PER_PIXEL = BITMAP_BITS_PER_PIXEL();
public static native @MemberGetter int BITMAP_BITS_PER_CHANNEL();
public static final int BITMAP_BITS_PER_CHANNEL = BITMAP_BITS_PER_CHANNEL();
public static native @MemberGetter int BITMAP_CHANNEL_COUNT();
public static final int BITMAP_CHANNEL_COUNT = BITMAP_CHANNEL_COUNT();

public static native @MemberGetter int JAB_SUCCESS();
public static final int JAB_SUCCESS = JAB_SUCCESS();
public static native @MemberGetter int JAB_FAILURE();
public static final int JAB_FAILURE = JAB_FAILURE();

public static native @MemberGetter int NORMAL_DECODE();
public static final int NORMAL_DECODE = NORMAL_DECODE();
public static native @MemberGetter int COMPATIBLE_DECODE();
public static final int COMPATIBLE_DECODE = COMPATIBLE_DECODE();

// #define VERSION2SIZE(x)		(x * 4 + 17)
// #define SIZE2VERSION(x)		((x - 17) / 4)
// #define MAX(a,b) 			({__typeof__ (a) _a = (a); __typeof__ (b) _b = (b); _a > _b ? _a : _b;})
// #define MIN(a,b) 			({__typeof__ (a) _a = (a); __typeof__ (b) _b = (b); _a < _b ? _a : _b;})

// #define JAB_REPORT_ERROR(x)	{ printf("JABCode Error: "); printf x; printf("\n"); }
// #define JAB_REPORT_INFO(x)	{ printf("JABCode Info: "); printf x; printf("\n"); }

/**
 * \brief 2-dimensional integer vector
*/
@Name("jab_vector2d") public static class JABVector2D extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public JABVector2D() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public JABVector2D(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public JABVector2D(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public JABVector2D position(long position) {
        return (JABVector2D)super.position(position);
    }
    @Override public JABVector2D getPointer(long i) {
        return new JABVector2D((Pointer)this).offsetAddress(i);
    }

	public native @Cast("jab_int32") int x(); public native JABVector2D x(int setter);
	public native @Cast("jab_int32") int y(); public native JABVector2D y(int setter);
}

/**
 * \brief 2-dimensional float vector
*/
@Name("jab_point") public static class JABPoint extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public JABPoint() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public JABPoint(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public JABPoint(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public JABPoint position(long position) {
        return (JABPoint)super.position(position);
    }
    @Override public JABPoint getPointer(long i) {
        return new JABPoint((Pointer)this).offsetAddress(i);
    }

	public native @Cast("jab_float") float x(); public native JABPoint x(float setter);
	public native @Cast("jab_float") float y(); public native JABPoint y(float setter);
}

/**
 * \brief Data structure
*/
@Name("jab_data") public static class JABData extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public JABData() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public JABData(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public JABData(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public JABData position(long position) {
        return (JABData)super.position(position);
    }
    @Override public JABData getPointer(long i) {
        return new JABData((Pointer)this).offsetAddress(i);
    }

	public native @Cast("jab_int32") int length(); public native JABData length(int setter);
	public native @Cast("jab_char") byte data(int i); public native JABData data(int i, byte setter);
	@MemberGetter public native @Cast("jab_char*") BytePointer data();
}

/**
 * \brief Code bitmap
*/
@Name("jab_bitmap") public static class JABBitmap extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public JABBitmap() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public JABBitmap(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public JABBitmap(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public JABBitmap position(long position) {
        return (JABBitmap)super.position(position);
    }
    @Override public JABBitmap getPointer(long i) {
        return new JABBitmap((Pointer)this).offsetAddress(i);
    }

   public native @Cast("jab_int32") int width(); public native JABBitmap width(int setter);
   public native @Cast("jab_int32") int height(); public native JABBitmap height(int setter);
   public native @Cast("jab_int32") int bits_per_pixel(); public native JABBitmap bits_per_pixel(int setter);
   public native @Cast("jab_int32") int bits_per_channel(); public native JABBitmap bits_per_channel(int setter);
   public native @Cast("jab_int32") int channel_count(); public native JABBitmap channel_count(int setter);
   public native @Cast("jab_byte") byte pixel(int i); public native JABBitmap pixel(int i, byte setter);
   @MemberGetter public native @Cast("jab_byte*") BytePointer pixel();
}

/**
 * \brief Symbol parameters
*/
@Name("jab_symbol") public static class JABSymbol extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public JABSymbol() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public JABSymbol(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public JABSymbol(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public JABSymbol position(long position) {
        return (JABSymbol)super.position(position);
    }
    @Override public JABSymbol getPointer(long i) {
        return new JABSymbol((Pointer)this).offsetAddress(i);
    }

	public native @Cast("jab_int32") int index(); public native JABSymbol index(int setter);
	public native @ByRef JABVector2D side_size(); public native JABSymbol side_size(JABVector2D setter);
	public native @Cast("jab_int32") int host(); public native JABSymbol host(int setter);
	public native @Cast("jab_int32") int slaves(int i); public native JABSymbol slaves(int i, int setter);
	@MemberGetter public native @Cast("jab_int32*") IntPointer slaves();
	public native @Cast("jab_int32") int wcwr(int i); public native JABSymbol wcwr(int i, int setter);
	@MemberGetter public native @Cast("jab_int32*") IntPointer wcwr();
	public native JABData data(); public native JABSymbol data(JABData setter);
	public native @Cast("jab_byte*") BytePointer data_map(); public native JABSymbol data_map(BytePointer setter);
	public native JABData metadata(); public native JABSymbol metadata(JABData setter);
	public native @Cast("jab_byte*") BytePointer matrix(); public native JABSymbol matrix(BytePointer setter);
}

/**
 * \brief Encode parameters
*/
@Name("jab_encode") public static class JABEncode extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public JABEncode() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public JABEncode(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public JABEncode(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public JABEncode position(long position) {
        return (JABEncode)super.position(position);
    }
    @Override public JABEncode getPointer(long i) {
        return new JABEncode((Pointer)this).offsetAddress(i);
    }

	public native @Cast("jab_int32") int color_number(); public native JABEncode color_number(int setter);
	public native @Cast("jab_int32") int symbol_number(); public native JABEncode symbol_number(int setter);
	public native @Cast("jab_int32") int module_size(); public native JABEncode module_size(int setter);
	public native @Cast("jab_int32") int master_symbol_width(); public native JABEncode master_symbol_width(int setter);
	public native @Cast("jab_int32") int master_symbol_height(); public native JABEncode master_symbol_height(int setter);
	/** Palette holding used module colors in format RGB */
	public native @Cast("jab_byte*") BytePointer palette(); public native JABEncode palette(BytePointer setter);
	public native JABVector2D symbol_versions(); public native JABEncode symbol_versions(JABVector2D setter);
	public native @Cast("jab_byte*") BytePointer symbol_ecc_levels(); public native JABEncode symbol_ecc_levels(BytePointer setter);
	public native @Cast("jab_int32*") IntPointer symbol_positions(); public native JABEncode symbol_positions(IntPointer setter);
	/** Pointer to internal representation of JAB Code symbols */
	public native JABSymbol symbols(); public native JABEncode symbols(JABSymbol setter);
	public native JABBitmap bitmap(); public native JABEncode bitmap(JABBitmap setter);
}

/**
 * \brief Decoded metadata
*/
@Name("jab_metadata") public static class JABMetadata extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public JABMetadata() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public JABMetadata(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public JABMetadata(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public JABMetadata position(long position) {
        return (JABMetadata)super.position(position);
    }
    @Override public JABMetadata getPointer(long i) {
        return new JABMetadata((Pointer)this).offsetAddress(i);
    }

	public native @Cast("jab_boolean") boolean default_mode(); public native JABMetadata default_mode(boolean setter);
	public native @Cast("jab_byte") byte Nc(); public native JABMetadata Nc(byte setter);
	public native @Cast("jab_byte") byte mask_type(); public native JABMetadata mask_type(byte setter);
	public native @Cast("jab_byte") byte docked_position(); public native JABMetadata docked_position(byte setter);
	public native @ByRef JABVector2D side_version(); public native JABMetadata side_version(JABVector2D setter);
	public native @ByRef JABVector2D ecl(); public native JABMetadata ecl(JABVector2D setter);
}

/**
 * \brief Decoded symbol
*/
@Name("jab_decoded_symbol") public static class JABDecodedSymbol extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public JABDecodedSymbol() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public JABDecodedSymbol(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public JABDecodedSymbol(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public JABDecodedSymbol position(long position) {
        return (JABDecodedSymbol)super.position(position);
    }
    @Override public JABDecodedSymbol getPointer(long i) {
        return new JABDecodedSymbol((Pointer)this).offsetAddress(i);
    }

	public native @Cast("jab_int32") int index(); public native JABDecodedSymbol index(int setter);
	public native @Cast("jab_int32") int host_index(); public native JABDecodedSymbol host_index(int setter);
	public native @Cast("jab_int32") int host_position(); public native JABDecodedSymbol host_position(int setter);
	public native @ByRef JABVector2D side_size(); public native JABDecodedSymbol side_size(JABVector2D setter);
	public native @Cast("jab_float") float module_size(); public native JABDecodedSymbol module_size(float setter);
	public native @ByRef JABPoint pattern_positions(int i); public native JABDecodedSymbol pattern_positions(int i, JABPoint setter);
	@MemberGetter public native JABPoint pattern_positions();
	public native @ByRef JABMetadata metadata(); public native JABDecodedSymbol metadata(JABMetadata setter);
	public native @ByRef JABMetadata slave_metadata(int i); public native JABDecodedSymbol slave_metadata(int i, JABMetadata setter);
	@MemberGetter public native JABMetadata slave_metadata();
	public native @Cast("jab_byte*") BytePointer palette(); public native JABDecodedSymbol palette(BytePointer setter);
	public native JABData data(); public native JABDecodedSymbol data(JABData setter);
}


public static native JABEncode createEncode(@Cast("jab_int32") int color_number, @Cast("jab_int32") int symbol_number);
public static native void destroyEncode(JABEncode enc);
public static native @Cast("jab_int32") int generateJABCode(JABEncode enc, JABData data);
public static native JABData decodeJABCode(JABBitmap bitmap, @Cast("jab_int32") int mode, @Cast("jab_int32*") IntPointer status);
public static native JABData decodeJABCodeEx(JABBitmap bitmap, @Cast("jab_int32") int mode, @Cast("jab_int32*") IntPointer status, JABDecodedSymbol symbols, @Cast("jab_int32") int max_symbol_number);
public static native @Cast("jab_boolean") boolean saveImage(JABBitmap bitmap, @Cast("jab_char*") BytePointer filename);
public static native @Cast("jab_boolean") boolean saveImageCMYK(JABBitmap bitmap, @Cast("jab_boolean") boolean isCMYK, @Cast("jab_char*") BytePointer filename);
public static native JABBitmap readImage(@Cast("jab_char*") BytePointer filename);
public static native void reportError(@Cast("jab_char*") BytePointer message);

// #endif


}
