#!/bin/bash

# organize.sh - Script to organize the JABCode codebase and place generated files in their appropriate places

# Create necessary directories
mkdir -p output/libs
mkdir -p output/docs
mkdir -p output/images
mkdir -p output/include

# Copy native libraries to output/libs
echo "Copying native libraries to output/libs..."
cp lib/libjabcode*.so output/libs/ 2>/dev/null || true
cp lib/libjabcode*.a output/libs/ 2>/dev/null || true
cp lib/libjabcode*.dll output/libs/ 2>/dev/null || true
cp lib/libjabcode*.dylib output/libs/ 2>/dev/null || true

# Copy JAR files to output/libs
echo "Copying JAR files to output/libs..."
cp javacpp-wrapper/target/*.jar output/libs/ 2>/dev/null || true

# Copy documentation to output/docs
echo "Copying documentation to output/docs..."
cp README*.md output/docs/ 2>/dev/null || true
cp -r docs/* output/docs/ 2>/dev/null || true

# Copy JABCode images to output/images
echo "Copying JABCode images to output/images..."
cp palette/jabcode_*.png output/images/ 2>/dev/null || true
cp test-output/jabcode_*.png output/images/ 2>/dev/null || true
cp output/jabcode_*.png output/images/ 2>/dev/null || true

# Copy header files to output/include
echo "Copying header files to output/include..."
cp src/jabcode/include/*.h output/include/ 2>/dev/null || true

# Create a README file in the output directory
echo "Creating README file in the output directory..."
cat > output/README.md << EOF
# JABCode Output Directory

This directory contains the output files generated by the JABCode build process.

## Directory Structure

- **libs/**: Contains the native libraries and JAR files
- **docs/**: Contains the documentation
- **images/**: Contains the JABCode images
- **include/**: Contains the header files

## JABCode Color Modes

JABCode supports the following color modes:

- Binary (2 colors): Black and white
- Quaternary (4 colors): Cyan, Magenta, Yellow, Black
- Octal (8 colors): CMYK + RGB + White
- Hexadecimal (16 colors): Extended color palette
- 32 colors: Extended color palette
- 64 colors: Extended color palette
- 128 colors: Extended color palette
- 256 colors: Extended color palette

For more information, see the documentation in the docs/ directory.
EOF

echo "Organization completed."
echo "Output files are in the output/ directory."
